FROM nvidia/opencl:runtime-ubuntu16.04

RUN apt-get update

# Install utilities
RUN apt-get install -y wget zip libgomp1

# Install from released zip package
RUN wget http://mcx.space/nightly/release/v2020/mmc-linux-x86_64-v2020.zip \
    -O /mmc-linux.zip && unzip /mmc-linux.zip -d /

WORKDIR /data
ENV PATH "${PATH}:/mmc/bin:/mmc/test:/mmc/speedtest"
CMD [ "mmc" ]
